//STATUS CODES
export const STATUS_CODE_UNAUTHORIZED = 401;
export const STATUS_CODE_BAD_REQUEST = 400;
export const STATUS_CODE_HTTP_204_NO_CONTENT = 204;

//REQUEST STATUS
export const BAD_REQUEST = "BAD_REQUEST";
export const GOOD_REQUEST = "GOOD_REQUEST";
